---
- resources:
    cpu: true
    cputemp: true
    uptime: true
    memory: true
    network: true
    disk:
      - /
      - /mnt/storage  # Sustituir por la ruta de montaje de tu almacenamiento masivo (HDD/SSD)

- datetime:
    text_size: md
    format:
      dateStyle: full
      timeStyle: short
      hour12: false
